# Generated by Django 2.1 on 2018-11-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(default='Bangalore', max_length=50)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
    ]
