# Generated by Django 2.1 on 2018-11-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='remarks',
        ),
    ]
